base:
  version: 0.0.1
  name: dousheng
  mode: dev
  port: 8080
  host: 127.0.0.1
  start_time: 2022-05-01
  machine_id: 1

log:
  savePath: log_out/
  fileName: log
  fileExt: .log
  maxSize: 10
  maxBackups: 5
  maxAge: 30

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: dousheng
  default_string_size: 256
  max_open_connection: 200
  max_idle_connecrtion: 50



server:
  Video:
    name: dousheng/video
    port: :8100