// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: comment.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Comment service

func NewCommentEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Comment service

type CommentService interface {
	CreateComment(ctx context.Context, in *CommentRequest, opts ...client.CallOption) (*CommentResponse, error)
	DeleteComment(ctx context.Context, in *CommentRequest, opts ...client.CallOption) (*CommentResponse, error)
}

type commentService struct {
	c    client.Client
	name string
}

func NewCommentService(name string, c client.Client) CommentService {
	return &commentService{
		c:    c,
		name: name,
	}
}

func (c *commentService) CreateComment(ctx context.Context, in *CommentRequest, opts ...client.CallOption) (*CommentResponse, error) {
	req := c.c.NewRequest(c.name, "Comment.CreateComment", in)
	out := new(CommentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentService) DeleteComment(ctx context.Context, in *CommentRequest, opts ...client.CallOption) (*CommentResponse, error) {
	req := c.c.NewRequest(c.name, "Comment.DeleteComment", in)
	out := new(CommentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Comment service

type CommentHandler interface {
	CreateComment(context.Context, *CommentRequest, *CommentResponse) error
	DeleteComment(context.Context, *CommentRequest, *CommentResponse) error
}

func RegisterCommentHandler(s server.Server, hdlr CommentHandler, opts ...server.HandlerOption) error {
	type comment interface {
		CreateComment(ctx context.Context, in *CommentRequest, out *CommentResponse) error
		DeleteComment(ctx context.Context, in *CommentRequest, out *CommentResponse) error
	}
	type Comment struct {
		comment
	}
	h := &commentHandler{hdlr}
	return s.Handle(s.NewHandler(&Comment{h}, opts...))
}

type commentHandler struct {
	CommentHandler
}

func (h *commentHandler) CreateComment(ctx context.Context, in *CommentRequest, out *CommentResponse) error {
	return h.CommentHandler.CreateComment(ctx, in, out)
}

func (h *commentHandler) DeleteComment(ctx context.Context, in *CommentRequest, out *CommentResponse) error {
	return h.CommentHandler.DeleteComment(ctx, in, out)
}
