base:
  version: 0.0.1
  name: dousheng
  mode: dev
  port: 8080
  host: 192.168.43.241
  start_time: 2022-05-01

log:
  savePath: log_out/
  fileName: log
  fileExt: .log
  maxSize: 10
  maxBackups: 5
  maxAge: 30

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: dousheng
  default_string_size: 256
  max_open_connection: 200
  max_idle_connecrtion: 50

redis:
  host: 192.168.141.101
  port: 6379
  db: 1
  password:
  pool_size: 100

etcd:
  address: 192.168.141.101:2379

duration:
  token: 90

server:
  video:
    machine_id: 1
    name: srv.video
    address: 127.0.0.1:8920
  comment:
    machine_id: 2
    name: srv.comment
    address: 127.0.0.1:8910
  user:
    machine_id: 3
    name: srv.user
    address: 127.0.0.1:8970
  favorite:
    machine_id: 4
    name: srv.favourite
    address: 127.0.0.1:8950
  relation:
    machine_id: 5
    name: srv.relation
    address: 127.0.0.1:8980