base:
  version: 0.0.1
  name: dousheng
  mode: dev
  port: 8080
  host: 127.0.0.1
  start_time: 2022-05-01
  machine_id: 1

log:
  savePath: log_out/
  fileName: log
  fileExt: .log
  maxSize: 10
  maxBackups: 5
  maxAge: 30

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password:
  db: dousheng
  default_string_size: 256
  max_open_connection: 200
  max_idle_connecrtion: 50

etcd:
  address: 127.0.0.1:2379


duration:
  token: 7

server:
  video:
    name: srv.video
    address: 127.0.0.1:8100
  comment:
    name: srv.comment
    address: 127.0.0.1:8088
  user:
    name: srv.user
    address: 127.0.0.1:8888